### ISSUE TITLE
Rename repo?

### ISSUE THREAD

**Issue by dwijnand** [lagom/lagom-minimal-deployment-sample#4]
I'd like to propose dropping the "minimal" and replacing "deployment" with "kubernetes" or "openshift".

"Minimal" is an adjective, like "simple" and "new" and "fast", so I would avoid it.

"Deployment", on the other hand, is too broad.  Will this eventually be an example of deploying to AWS? To GCE?  If it's just targeting Kubernetes and OpenShift I think it should be called one of the following (and I can see arguments for either, so I'm ambivalent):

* `lagom-scala-kubernetes-example` or
* `lagom-scala-openshift-example`

**Comment by ignasi35** [comment]
After more discussion we settled on something like:

 - `lagom-scala-openshift-smoketests`

**Comment by dwijnand** [comment]
WFM!

**Comment by ignasi35** [comment]
NOTE: the rename will require a full string replacement across the project (`build.sbt`, `*.yml`,...)
